// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: greeter.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "gogotest.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "gogotest.HelloReply")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x8f, 0x3f, 0x4b, 0xc4, 0x30,
	0x18, 0xc6, 0x29, 0xa8, 0x3d, 0x5f, 0x3c, 0x87, 0x20, 0x72, 0xc4, 0x41, 0xe9, 0x20, 0x4e, 0x39,
	0xd1, 0xc5, 0xc5, 0x45, 0x38, 0x74, 0xbe, 0xde, 0xe4, 0x96, 0x1e, 0x8f, 0xa1, 0xd0, 0x98, 0x9a,
	0xbc, 0x15, 0xfa, 0x2d, 0xfd, 0x48, 0xd2, 0xc4, 0x80, 0xd8, 0xcd, 0x29, 0xc9, 0x93, 0xdf, 0xfb,
	0xe7, 0x47, 0x4b, 0xe3, 0x01, 0x86, 0x57, 0xbd, 0x77, 0xec, 0xc4, 0xc2, 0x38, 0xe3, 0x18, 0x81,
	0xe5, 0x85, 0x71, 0xce, 0x74, 0x58, 0xc7, 0xbc, 0x19, 0xde, 0xd6, 0xb0, 0x3d, 0x8f, 0x09, 0x93,
	0x97, 0x7f, 0x3f, 0xb9, 0xb5, 0x08, 0xac, 0x6d, 0x9f, 0x80, 0xaa, 0xa2, 0x93, 0x17, 0x74, 0x9d,
	0xdb, 0xe2, 0x63, 0x40, 0x60, 0x21, 0xe8, 0xe0, 0x5d, 0x5b, 0xac, 0x8a, 0xab, 0xe2, 0xe6, 0x78,
	0x1b, 0xef, 0xd5, 0x35, 0xd1, 0x0f, 0xd3, 0x77, 0xa3, 0x58, 0x51, 0x69, 0x11, 0x82, 0x36, 0x19,
	0xca, 0xcf, 0xbb, 0xaf, 0x82, 0x4e, 0x9f, 0xd3, 0x96, 0x35, 0xfc, 0x67, 0xbb, 0x87, 0x78, 0xa0,
	0x45, 0xad, 0xc7, 0x58, 0x2d, 0xce, 0x55, 0xde, 0x59, 0xfd, 0x1e, 0x29, 0xcf, 0x66, 0xf9, 0x34,
	0xe6, 0x91, 0xca, 0x5a, 0x8f, 0xbb, 0xd6, 0x22, 0x16, 0x4e, 0x16, 0x2a, 0x5b, 0xa8, 0xcd, 0xa4,
	0x28, 0xe5, 0x2c, 0xdf, 0x65, 0x3b, 0xb1, 0xa1, 0x65, 0x3d, 0x34, 0x61, 0xef, 0xdb, 0x06, 0xff,
	0x6d, 0x72, 0x5b, 0x3c, 0x95, 0xaf, 0x87, 0x29, 0x3f, 0x8a, 0xc7, 0xfd, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x9c, 0xe5, 0xd8, 0x11, 0x87, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterServiceClient is the client API for GreeterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayTime(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*types.Timestamp, error)
	SubscribeTime(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (GreeterService_SubscribeTimeClient, error)
}

type greeterServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreeterServiceClient(cc *grpc.ClientConn) GreeterServiceClient {
	return &greeterServiceClient{cc}
}

func (c *greeterServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/gogotest.GreeterService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) SayTime(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (*types.Timestamp, error) {
	out := new(types.Timestamp)
	err := c.cc.Invoke(ctx, "/gogotest.GreeterService/SayTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterServiceClient) SubscribeTime(ctx context.Context, in *types.Empty, opts ...grpc.CallOption) (GreeterService_SubscribeTimeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreeterService_serviceDesc.Streams[0], "/gogotest.GreeterService/SubscribeTime", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterServiceSubscribeTimeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreeterService_SubscribeTimeClient interface {
	Recv() (*types.Timestamp, error)
	grpc.ClientStream
}

type greeterServiceSubscribeTimeClient struct {
	grpc.ClientStream
}

func (x *greeterServiceSubscribeTimeClient) Recv() (*types.Timestamp, error) {
	m := new(types.Timestamp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServiceServer is the server API for GreeterService service.
type GreeterServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayTime(context.Context, *types.Empty) (*types.Timestamp, error)
	SubscribeTime(*types.Empty, GreeterService_SubscribeTimeServer) error
}

func RegisterGreeterServiceServer(s *grpc.Server, srv GreeterServiceServer) {
	s.RegisterService(&_GreeterService_serviceDesc, srv)
}

func _GreeterService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gogotest.GreeterService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_SayTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServiceServer).SayTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gogotest.GreeterService/SayTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServiceServer).SayTime(ctx, req.(*types.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreeterService_SubscribeTime_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(types.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServiceServer).SubscribeTime(m, &greeterServiceSubscribeTimeServer{stream})
}

type GreeterService_SubscribeTimeServer interface {
	Send(*types.Timestamp) error
	grpc.ServerStream
}

type greeterServiceSubscribeTimeServer struct {
	grpc.ServerStream
}

func (x *greeterServiceSubscribeTimeServer) Send(m *types.Timestamp) error {
	return x.ServerStream.SendMsg(m)
}

var _GreeterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gogotest.GreeterService",
	HandlerType: (*GreeterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreeterService_SayHello_Handler,
		},
		{
			MethodName: "SayTime",
			Handler:    _GreeterService_SayTime_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeTime",
			Handler:       _GreeterService_SubscribeTime_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "greeter.proto",
}
